### PR TITLE
Fix/focus/4713

### LINKED ISSUE #4713: Lost focus on 'select2:open' when using 'minimumResultsForSearch' option.
I was having an issue similar to #3279 : I hit enter, dropdown is open, but I'm not able to navigate or search. The focus seems to go to another "place". I had to click and then it becomes navigable/search-able with keyboard.

But I think is the weird think. I another page, this works fine. 

So, I noticed that only difference was the `minimumResultsForSearch` option: 

```js
options: {
  minimumResultsForSearch: 7,
  ajax: { 
    // . . .
  }
}
```

When I remove `minimumResultsForSearch`, then works fine.

**For now, I'm disabling `minimumResultsForSearch` option**

> PD: Sorry for the incomplete/bare report, I've much time right now. But I will make some tests later and update this report with falling tests to discard or reproduce, because this option is very useful.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: `2.2.4`
- Select2 version: `4.0.3`

### PR DESCRIPTION
**Pull request by shark-horse**
This pull request includes a
- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made
- Fixed #4713 by focusing the dropdown in cases where the search box is not visible. This allows keyboard input to be processed properly.
- related integration tests
- Fixed .css reference in integration.html, required for certain behavior in new tests.
- Added a cleanup routine to remove the elements that select2 appends to the body, for repeatable tests.
- easier building from the command line for my own sanity: `npm run build` to build everything, `npm grunt xyz` to run arbitrary grunt commands, and we use the version of grunt prescribed in package.json rather than whatever you have installed globally at the time.

If this is related to an existing ticket, include a link to it as well.
#4713

### CODE REVIEW

**Comment by shark-horse** [comment]
I seem to have erred again. Let me check the history.

**Comment by alexweissman** [comment]
It should be possible to just modify your PR instead of opening a new one each time, no?

**Comment by shark-horse** [comment]
Previously, when I would rebase a branch, I saw no way in the Gitlab UI to reopen the PR. I found some directions online for doing it involving some Git-fu, but I don't think that would achieve what I wanted (looked like it would effectively undo what I was trying to do with the rebase), so I just created another PR.

What should I try to merge into? For this PR to be focused on our one cited issue, I should only request to merge in related commits that I made, all the commits in the RC that haven't been merged into master, right?

**Comment by alexweissman** [comment]
Release candidates will be released off of `develop`, and full release versions will be released off `master` after `develop` is merged back in.  I don't use GitHub's auto-merge feature, so I will actually end up manually reviewing and cherry-picking your commits.

That being said, it would probably be easiest if you submitted one PR per issue.  Most of your changes seem fairly innocuous, but I may hold off on merging anything related to element focus, since there have been so many other recent issues with losing focus that I want to get fixed first.

If you could join me in my [chat](https://chat.userfrosting.com), that would make it easier for me to understand the remaining issues with focus.

**Comment by shark-horse** [comment]
Ok. Do I need to change what branch I'm merging into, or leave this PR alone?

**Comment by kevin-brown** [comment]
Unfortunately this pull request contains files in the `dist` folder, and as a result there is a merge conflict. Because this pull request is also pretty old (our fault), we are closing this off.

If you are still interested in making this contribution, feel free to remove the `dist` changes from this pull request and leave a comment asking for this to be re-reviewed. Or make a new pull request from the same branch, and we'll try to get around to reviewing it this time.

**Pull request closed without merging**
