### PR TITLE
Fix for issue #4632

### PR DESCRIPTION
**Pull request by julianyus**
This pull request includes a

- [ x ] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- I have changed the way in which an item is determined to be a simple object
- I have created some tests to verify that a user-defined object is correctly normalized

Issue: https://github.com/select2/select2/issues/4632

### CODE REVIEW

**Comment by alexweissman** [comment]
Nice!  I'm hoping to get a release candidate out for 4.0.5 soon.

**Comment by alexweissman** [comment]
@julianyus it looks like the last two assertions in `select-tests` are failing for me in Firefox:

screen shot 2017-10-25 at 1 46 19 pm

Seems like `normalizedItem3.id` and `normalizedItem3.text` are returning objects, not scalars.

**Comment by julianyus** [comment]
@alexweissman 
To me it works in firefox.
Did you do "grunt compile"? I did not include the compiled files (dist folder) in the commit.

**Comment by alexweissman** [comment]
> Did you do "grunt compile"?

d'oh!  Thanks, I always forget that the tests are pulling from `dist/` ☹️ 

Ok this looks good, I'll put it out in the RC.

**Comment by alexweissman** [comment]
Merged into `develop` for 4.0.6 release.

**Pull request closed without merging**
