### PR TITLE
css optimization #5226

### PR DESCRIPTION
**Pull request by webjohan**
Smal css  optimization

This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Minor improvement

The following changes were made

- Improved/optimisation of scss/css
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by webjohan** [comment]
Pull request #5227

**Comment by smajl** [comment]
Why did you remove the variable and hardcoded 4px?

**Comment by webjohan** [comment]
Im not sure. This was a long time ago.

But as I read it, this lines are removed:
      border-radius: 0;
      border-top-left-radius: $border-radius;
      border-bottom-left-radius: $border-radius;
and this one is added:
      border-radius: 4px 0 0 4px;
Which should have been:
      border-radius:  $border-radius 0 0  $border-radius;

I guess.

**Comment by smajl** [comment]
Your guess is correct.

**Comment by webjohan** [comment]
we should probably close this

**Pull request closed without merging**
