### PR TITLE
Docs for: What should the results returned to Select2 look like?

### PR DESCRIPTION
**Pull request by sedrubal**
This pull request includes a
- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Documentation

The following changes were made
- Added docs for chapter `What should the results returned to Select2 look like?`

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by nelson6e65** [comment]
I'm just guessing while I'm using... But the basic format of returning JSON (I've noticed until now) used by select2:

### Direct results

```js
{
  "results": [
    { "id": 1, "text": "Option 1" },
    { "id": 2, "text": "Option 2" },
    { "id": 3, "text": "Option 3" },
    //, { "id": <n>, "text": "Option <n>" }
],
  "paginate": {
    "more": true  // If this is true, select2 will send `"page": <n>` in order to request next page elements.
  }
}
```


### Grouped results

```js
{
  "results": [
    { 
      "text": "Group 1", 
      "children" : [
        { "id": 1, "text": "Option 1.1" },
        { "id": 2, "text": "Option 1.2" },
        { "id": 3, "text": "Option 1.3" },
        //,   { "id": <n>, "text": "Option 1.<n>" },
      ]
    },
    { 
      "text": "Group 2", 
      "children" : [
        { "id": 4, "text": "Option 2.1" },
        { "id": 5, "text": "Option 2.2" },
        { "id": 6, "text": "Option 2.3" },
        //, { "id": <n>, "text": "Option 2.<n>" },
      ]
    }
    //, { "text": "Group <n>", "children": optionsListArray }
  ],
  "paginate": {
    "more": true // There is more results, so select2 will request next page in the request 
                 // if user scroll to more than max. items per page returned in current "results".
  }
}
```

**Comment by alexweissman** [comment]
There appear to be multiple PRs addressing this section:

#5002 
#4863 
#4861 
#4814
#4662 

We should pick one of these, or integrate several to provide the most comprehensive answer.

**Comment by alexweissman** [comment]
This has been merged with some of the other PRs for this section, and is now reflected on the live docs.  See http://select2.github.io/options.html#what-should-the-results-returned-to-select2-look-like

@nelson6e65 Could you create a new PR with your documentation of grouped results?

**Comment by nelson6e65** [comment]
Oh! Nice! :smiley:

**Comment by alexweissman** [comment]
No problem.  If you want to talk about other possible improvements to the Select2 docs, I've set up a new room on my chat server: https://chat.userfrosting.com/channel/select2

**Pull request merged**
