### PR TITLE
Fix https://github.com/select2/select2/issues/4276

### PR DESCRIPTION
**Pull request by UksusoFF**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Change mousedown to click event. Fix for https://github.com/select2/select2/issues/4276

### CODE REVIEW

**Comment by alexweissman** [comment]
There are some other issues related to `mousedown` vs `click` events:

- #4763 (addressed in #4536)
- #4642 (addressed in #4644)
- https://github.com/select2/select2/issues/4482#issuecomment-264916443
- https://github.com/select2/select2/issues/4276#issuecomment-212663921

Actually #4276 makes a good point:

> Simply changing the opening event from `mousedown` to `click` fixes it, at the cost of losing functionality parity with a base `<select>` element.
A small (humanly imperceptible) delay between an opening `mousedown` and a selecting `mouseup` may be another way around it (ie, within the range of a normal 'click'), but again is not all that ideal.
Perhaps just an option on which event to listen for...?

Could you review these please?  It sounds like `mousedown` was originally used instead of `click` because of the behavior of mobile browsers, but this behavior has since been removed from most mobile browsers.  

I just want to make sure we don't introduce any new regressions.  It sounds like maybe a configuration setting for this might still be worthwhile, even if we change the default to be `click`?

**Comment by UksusoFF** [comment]
@alexweissman 
Checked this fix for a long time in Chrome/Safari on Mac OS X. 
Checked in Android Firefox/Chrome, iOS Safari/Chrome, Windows Chrome/Firefox/IE just now.

Looks like all of this issues have same trouble because dropdown overlap selection container:
https://github.com/select2/select2/issues/4763
https://github.com/select2/select2/issues/4642
https://github.com/select2/select2/issues/4276

I can't check this issue:
https://github.com/select2/select2/issues/4482
But if `mousedown` really not fired in iOS WebView (found many questions about it on StackOverflow [e.g.](https://stackoverflow.com/questions/26885670/mouseup-and-mousedown-not-working-on-ios)) PR must be help.

I don't think that need to configure that because we can bind `$('#mySelect2').select2('open');` on any actions.

**Comment by alexweissman** [comment]
Ok so as far as #4644 goes, do you think we should leave it as `click` in the multi-select case?

I'm actually not quite sure how this PR addresses #4200 - that issue seems to be related to `mouseup`, not `mousedown`.  Could you explain further?

**Comment by UksusoFF** [comment]
> I'm actually not quite sure how this PR addresses #4200 - that issue seems to be related to mouseup, not mousedown. Could you explain further?
My bad. I mentioned wrong issue.

> Ok so as far as #4644 goes, do you think we should leave it as click in the multi-select case?
What must occur when we click in Alaska in provided example? https://jsfiddle.net/vwsg4tn5/ 
We can delete item by cross. And we can show dropdown by clicking on Alaska. I don't think this behavior is wrong.

**Comment by alexweissman** [comment]
So, #4642 and #4295 describe some potential issues with using `click` for multi-select.

**Comment by alexweissman** [comment]
@UksusoFF it seems like this is not a good fix in the long term.  See my comment at https://github.com/select2/select2/issues/4276#issuecomment-334624014.

**Comment by UksusoFF** [comment]
Okay let's continue in issue.

**Pull request closed without merging**
