### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by blikblum**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Dependency update

The following changes were made

- Update most of the dev dependencies
- grunt-contrib-qunit is not updated to latest version because it conflicts with almond. The newest version compatible with almond loader is 0.5. This avoids to update grunt
- Update travis CI node version to 8 (oldest supported node)

This removes most of the build warnings / dependency vulnerabilities

### CODE REVIEW

**Comment by kevin-brown** [comment]
> * grunt-contrib-qunit is not updated to latest version because it conflicts with almond

Do you happen to have a link to somewhere that states this? I believe you, I just didn't find anything when I did a quick search.

**Comment by blikblum** [comment]
This is the affecting commit https://github.com/gruntjs/grunt-contrib-qunit/commit/db075a2b0a5e0f00390f39538cf6d18ff098673a

The select2 loader will try to load qunit module and fail

**Comment by blikblum** [comment]
Not a problem of almond at all, but a conflict between how the qunit-grunt runs and select2 loader

**Comment by kevin-brown** [comment]
This was merged in through https://github.com/select2/select2/pull/5529. I recompiled the dist files there and double checked that the resulting files are compatible (they are).

**Pull request closed without merging**
