### PR TITLE
Fix compatibility with jquery-3.4.0

### PR DESCRIPTION
**Pull request by borisson**
See issue #5485

This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

If this is related to an existing ticket, include a link to it as well.
https://github.com/select2/select2/issues/5485

### CODE REVIEW

**Comment by mkutlu** [comment]
This is not solved problem for IE, it just work for chrome.

**Comment by blikblum** [comment]
> 
> 
> This was not solved problem for IE, it just work for chrome.

I tested with IE 11 and is working

**Comment by kevin-brown** [comment]
Hi there, and thanks for the pull request to Select2.

Since this is fixing something which has already broken, we prefer it if the pull request includes a failing test case. With a failing test case, we don't need to worry about breaking this specific case again in the future, which saves us all a lot of time and trouble.

**Comment by borisson** [comment]
@kevin-brown I'm sorry - I won't be able to include a testcase. We've since switched to a different library so I won't get company time and I maintain my own project(s) so most of my limited free time goes to that. I understand why you'd want a test - sorry I won't be able to provide that.

**Comment by kevin-brown** [comment]
Should ultimately be fixed by https://github.com/select2/select2/pull/5558.

**Pull request closed without merging**
