### PR TITLE
Added an option to disable the selection search box in multiple mode

### PR DESCRIPTION
**Pull request by dimmelsw**
This pull request includes a
- [x] New feature

The following changes were made
The option `disableSelectionSearch` is added to hide the search input box in multiple selects.

### CODE REVIEW

**Comment by kevin-brown** [comment]
Right now I don't see this gaining a lot of traction as a common feature request. Because Select2 already has a large amount of things in the core, we prefer a new option gains traction in a feature request (non-pull request, a ticket) before we add it to the core builds.

**Comment by kevin-brown** [comment]
I would encourage you to recreate this as a standard issue in the tracker, referencing this pull request, and we can revisit it further down the line to see if this can land in the core or as a third-party extension to Select2.

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.

**Pull request closed without merging**
