### PR TITLE
Fixups: post-merge updates related to PR #6241

### PR DESCRIPTION
**Pull request by jayaddison**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Instead of referring to (QUnit) `test` in an integration test added by #6241, use the fully-qualified reference `QUnit.test` instead, as becomes standard after #6334.
- Add some guard conditions to `selection:update` event handlers in the integration tests, because these are not isolated from each other at test runtime, and otherwise may delay/timeout unrelated test cases.
- Regenerate distributable content.
- Regenerate NPM lockfile.

If this is related to an existing ticket, include a link to it as well.

Relates-to / merge-resolution-for #6241 and #6334.

Edit: add additional fixup descriptions.

### CODE REVIEW

**Comment by jayaddison** [comment]
Hmm.. I have a feeling that the test failure here (a timeout, essentially) was what I encountered locally before adding a `defer="defer"` attribute to the `<script>` elements in the test HTML files, to guarantee that they are [loaded in-order](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).

I think that somehow relates to the usage of AJAX in the tests, but I forget exactly why (or perhaps never quite pinpointed the reason).

**Comment by jayaddison** [comment]
> Hmm.. I have a feeling that the test failure here (a timeout, essentially) was what I encountered locally before adding a `defer="defer"` attribute to the `<script>` elements in the test HTML files, to guarantee that they are [loaded in-order](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).
> 
> I think that somehow relates to the usage of AJAX in the tests, but I forget exactly why (or perhaps never quite pinpointed the reason).

I fully admit that it may seem spammy or unnecessary, but I believe that #6336 should resolve this problem.

**Comment by jayaddison** [comment]
> > Hmm.. I have a feeling that the test failure here (a timeout, essentially) was what I encountered locally before adding a `defer="defer"` attribute to the `<script>` elements in the test HTML files, to guarantee that they are [loaded in-order](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).
> > I think that somehow relates to the usage of AJAX in the tests, but I forget exactly why (or perhaps never quite pinpointed the reason).
> 
> I fully admit that it may seem spammy or unnecessary, but I believe that #6336 should resolve this problem.

That pull request did not appear to resolve the problem, and so further investigation is required.

**Comment by jayaddison** [comment]
@kevin-brown something about the `searching tags does not loose focus` integration test seems incompatible with #6241 -- I've commented it out here, and that allows the test suite to pass, but it's not an approach I like so I've moved this into draft status until the problem is figured out.

**Comment by jayaddison** [comment]
The problem seems to be that `selection:update` event handling in the integration tests isn't isolated per-test-case.  Some ideas to resolve this:

  * Add some kind of per-test teardown that removes relevant event handling/selection-update resources (listeners, DOM contents, internal state?).
  * Attach once-only event handlers in each of the relevant integration test cases.
  * Add logic to ensure that each event-handler becomes essentially a no-op despite remaining attached during unrelated integration tests.

I attempted to add a [`QUnit.reset` handler from here](https://github.com/qunitjs/qunit/issues/630#issuecomment-52478879) to achieve the first; but this did not seem to work.

The second approach doesn't appear straightforward either; there is no `.once(...)` function available for event-listener attachment on `Select2` instances, nor is there a way to pass `{once: true}` as a parameter to `.on(...)`.

...so I've slightly-reluctantly implemented the third approach.  It doesn't genuinely provide any meaningful runtime isolation between the integration test cases, but it ensure that each event listener should only perform any actions within the scope of its parent test case.

**Comment by jayaddison** [comment]
@kevin-brown it's not ideal code (details in my previous message if you're curious), but I believe this is ready for merge.

**Review by kevin-brown — APPROVED** [review]

**Comment by kevin-brown** [comment]
I'll take the "temporary" hack for now. Thanks for looking into this and documenting your findings!

**Pull request merged**
