### PR TITLE
Adding sample JSON object to Ajax documentation

### PR DESCRIPTION
**Pull request by adw99**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

Hi, I'm just trying to add a sample JSON object to the Ajax documentation - it would have saved me a little time when I was looking for it. The change is in docs\_includes\options\data\ajax.html. Please take a look and let me know what you think.

### CODE REVIEW

**Comment by TheRealGitCub** [comment]
It would be also worth adding that the `id` attribute is required, and must start at 1.

**Comment by alexweissman** [comment]
There appear to be multiple PRs addressing this section:

#5002 
#4863 
#4861 
#4814
#4662 

We should pick one of these, or integrate several to provide the most comprehensive answer.

**Comment by alexweissman** [comment]
Not sure what `"status" : 200` does in the context of Select2, but the pagination info is useful.

**Comment by alexweissman** [comment]
Thanks, this has been merged with some of the other PRs for this section, and is now reflected on the live docs.  See http://select2.github.io/options.html#what-should-the-results-returned-to-select2-look-like

**Pull request closed without merging**
