### PR TITLE
Add select2.min.js to scripts list

### PR DESCRIPTION
**Pull request by Restless-ET**

### CODE REVIEW

**Comment by kevin-brown** [comment]
Is there any particular reason why this is done?

Typically only the uncompiled assets are included here so they can be integrated into build systems down the line. Minifying already minifed assets has a tendency to cause really strange glitches.

**Comment by Restless-ET** [comment]
When I fetch this as a bower asset I get the minified version, so I was just trying to mimic the same behaviour when fetching as a composer component.

I can use bower so it's not a limitation for me.

If you believe this doesn't make sense feel free to close the PR. No hard feelings. :)

**Comment by kongr45gpen** [comment]
BTW, is there any reason that the full select2.js file is not included with composer?

**Comment by grappler** [comment]
http://stackoverflow.com/a/21266210/850651

**Comment by kevin-brown** [comment]
> BTW, is there any reason that the full select2.js file is not included with composer?

For consistency with other distribution platforms.

**Pull request closed without merging**
