### PR TITLE
Fixing bug with non-static parents for dropdowns

### PR DESCRIPTION
**Pull request by rcousart**
This pull request includes a

- [X] Bug fix

The following changes were made

- Added `parentOffset` to the computation of the `css.top` when direction is above

This fix adds the offset to the case where the dropdown direction is above as seen and resolved in #3303

### CODE REVIEW

**Comment by kevin-brown** [comment]
I can test this out, but it would be useful if we could also get a unit test that covers this (similar to the [existing ones](https://github.com/select2/select2/blob/6844be777b0fe9af1d2b9a8f6051b7eb7d532247/tests/dropdown/positioning-tests.js)) so we can ensure that this bug doesn't come back in the future.

**Comment by rcousart** [comment]
@kevin-brown good idea, will add that shortly

**Comment by rcousart** [comment]
I believe this logic triggers only when there is a class in the `span` block inside of the select container that specifies the direction of the dropdown. I added the class `select2-dropdown--below` and `select2-dropdown--above` and ran the current test that checks for offset. 

Can anyone take a look and see if this is actually doing what I want it to? I would love some advice on how to test this better to ensure this doesn't break in future changes.

**Comment by lvlalbert** [comment]
I'm having a problem when the dropdown is above and not below. The offsets do not get reset when the dropdown closes or something along those lines. Does this fix that? I tried this by replacing the lines in select2.js but it didn't work. Here is an image detailing my issue. 
https://i.imgur.com/8BaP5ND.jpg
Any ideas?
Thanks. This is my first time posting on GitHub.

**Comment by kevin-brown** [comment]
I have committed https://github.com/select2/select2/pull/4267/commits/edee884abe4246871afb1731250f1aa9fc0dc845 as https://github.com/select2/select2/commit/ecdc41663508f0a5ea242fe249aa5a9a3a741ba6. I did not include the tests, because after playing around with them it hit me that they do not actually fail without the change. I did modify the existing tests in https://github.com/select2/select2/commit/98f054fc18d4eabe104153cbab0bc6447456d310 to check that the classes are automatically being applied to the dropdown.

Thanks for the initial pull request to fix this issue. You should see it fixed in the upcoming 4.0.3 release.

**Comment by Loadmaster** [comment]
I had the same problem, where the drop-down was being positioned too far down (too large a `top` value) on the page when the Select2 element was contained within a table `<td>` element.

In my situation, the problem was that the (non-`static`) parent's position was being added to the drop-down's `top` offset, when it should _not_ have been.

See #4382 for details and my suggested code fix.

**Pull request closed without merging**
