### PR TITLE
Add, add option dynamically functionality

### PR DESCRIPTION
**Pull request by syndbg**
Addresses #2830 .

The `addOption` works perfectly fine with anything but some AJAX Adapter using select inputs.

I'm open to suggestions on how to address the majority of ajax select inputs.

### CODE REVIEW

**Comment by kevin-brown** [comment]
It _looks_ like you might need to rebase this pull request against the latest version of `master`. I'm leaning more towards this being a helper method ([similar to `select2_search`](http://stackoverflow.com/q/30517128/359284#30552284)) as it shouldn't _(in theory)_ actually require changes to the Select2 core codebase.

You also might want to look into [`ArrayAdapter.prototype.convertToOptions`](https://github.com/select2/select2/blob/6be96cfaa175448ef70b978648de7d6cb5822e89/src/js/select2/data/array.js#L30-L76) for some of the special cases involved with this. And [`SelectAdapter.prototype.option`](https://github.com/select2/select2/blob/6be96cfaa175448ef70b978648de7d6cb5822e89/src/js/select2/data/select.js#L157-L198) for converting a data object to an `<option>` element.

**Comment by syndbg** [comment]
@kevin-brown I totally overslept this PR and just noticed your reply. 😊 

Is this still needed? I haven't used Select2 in a long time.

**Comment by aried3r** [comment]
Personally, I'd love to have this in select2, as well as may others (see #2830) it seems.

**Comment by syndbg** [comment]
@aried3r Great! I'll get this going in the following days. (Currently at work).

**Comment by aried3r** [comment]
Sounds great, thanks!

**Comment by alexweissman** [comment]
This would be a great feature.  The changes in `dist/` need to be removed, though, and we also need some automated tests.

**Comment by kevin-brown** [comment]
Unfortunately this pull request contains files in the `dist` folder, and as a result there is a merge conflict. Because this pull request is also pretty old (our fault), we are closing this off.

If you are still interested in making this contribution, feel free to remove the `dist` changes from this pull request and leave a comment asking for this to be re-reviewed. Or make a new pull request from the same branch, and we'll try to get around to reviewing it this time.

**Pull request closed without merging**
