### PR TITLE
Cache objects in Utils.__cache instead of using $.data (#4014)

### PR DESCRIPTION
**Pull request by NadeemAfana**
This pull request includes a
- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made
- Cache objects in `Utils.__cache` instead of using $.data 
- Updated several files to use the new functions to cache data in `Utils.__cache`
-  Removed all `$.data` code 

This is a bug fix for #4014

### CODE REVIEW

**Comment by kevin-brown** [comment]
There are indentation changes in here that are going to prevent this from being merged in.

**Comment by NadeemAfana** [comment]
I will fix the indentation.

**Comment by kevin-brown** [comment]
- There are still some indentation issues
- This is going to need integration tests to make sure that we don't have this issue in the future

**Comment by NadeemAfana** [comment]
Sorry for the indentation issues. I fixed the EOL to be UNIX format. My editor had switched this to Windows format.

Do you want me to add integration tests ?

**Comment by alexweissman** [comment]
There's an integration test now...can this be merged in?

**Comment by alexweissman** [comment]
Merged into `develop` for 4.0.6 release.

**Comment by oh-ren** [comment]
Please also consider the following discussion regarding `$myOriginalSelectElement.data('select2')`: https://github.com/select2/select2/issues/5071#issuecomment-340218988

**Comment by chrisdeeming** [comment]
Sorry for posting here, but it feels relevant and I've tried to get support from the official channels with no answers yet.

Although there’s a fallback in `Utils.GetData` to get from the data attribute if the cache is empty, there’s nothing that actually sets the data attribute in the first place.

What I’m trying to do is access what was equivalent to:

```js
var instance = $element.data('select2');
```

But this no longer seems to be possible.

Is there a public way of accessing the `GetData` or `SetData` functions?

Is this not a sort of dangerous change to make in essentially a bug fix release in terms of breaking backwards compatibility?

**Comment by alexweissman** [comment]
I'm here, just been busy with php[world] and traveling.

**Comment by chrisdeeming** [comment]
To be fair, I've not exactly been waiting long for a reply (and it's a weekend!), but I didn't necessarily want to see this one slip into a stable release if there's something wrong.

**Comment by alexweissman** [comment]
Yes, thanks @oh-ren and @chrisdeeming.  I didn't realize that these changes affected the public API.

But, it seems like this is meant to fix a bug (#4014).  Honestly, I don't really understand the problem that this is solving as I have never encountered this myself.  It seemed like a safe change, but apparently not.

Is there a way we can fix this bug (whatever it may be) without causing a breaking change?  Join me on my own chat server (https://chat.userfrosting.com/channel/select2) and we can discuss.

**Comment by alexweissman** [comment]
@NadeemAfana any thoughts on this?  Seems like this is breaking a lot of other aspects of Select2.

**Comment by NadeemAfana** [comment]
`$element.data('select2')` is clearly not public API; it is an internal implementation which people should avoid. Nonetheless, I will push a fix for this.

**Comment by alexweissman** [comment]
Thanks!  Yes, unfortunately Select2 is so big and widely used, and had been poorly documented for so long, and tends to attract the greenest types of developers, that it's part of the public API whether we want it to be or not 😦 

Are there any use cases where people really _need_ to be able to access `data('select2')`?  Otherwise we can add something to the documentation and then deprecate it over time.

Also, is there any chance that this modification is what is causing #5133?

**Comment by NadeemAfana** [comment]
I would definitely deprecate `.data('select2')`. It makes things confusing when people start using the internal components as they change over time. For example, updating `.data('select2').options.options.maximumSelectionLength` directly has no effect. According to [this comment,](https://github.com/select2/select2/issues/5071#issue-263367289)  it worked in the past, but this change has nothing to do with this PR.

> Also, is there any chance that this modification is what is causing #5133?

No, because I was able to reproduce the issue with `4.0.5`.

**Comment by chrisdeeming** [comment]
We use the data stored there specifically to access the elements which are dynamically created by Select2, mostly as a shortcut.

They are, specifically `.select2-container` and `.select2-selection`.

We could just find them in the DOM relative to element we've instantiated Select2 on but if they're already cached in the Select2 object then, why not?

Point taken about invalid use cases but that's not something we'd do.

**Comment by oh-ren** [comment]
I suggest to create a new method then, perhaps `$mySelect.select2('getInstance')`?
To reiterate *my* use case (there might be others of course) here: add a class to `$container` when the select is deemed `invalid` (for styling purposes).

Not sure how other (popular) jQuery plugins implement getting a reference / access to the internal instance. It's not something uncommon, or is it?
Anyway it provides a means to get things done that otherwise are impossible / the plugin doesn't cater for. Manually selecting based on classes (or manual DOM traversal) is like 10000 times worse than being able to access the relevant elements already constructed by Select2 itself.

(Off topic, but somewhat related: `$('#mySelect2').hasClass("select2-hidden-accessible")` is not that great, why not something like: `$('#mySelect2').select2('isInitialized')`?

@alexweissman Thanks for the invite, might check the channel out, but simply discussing here works best?

**Comment by chrisdeeming** [comment]
@oh-ren I would indeed say that something similar to `$mySelect.select2('getInstance')` is generally the norm in other libraries.

That said, the data attribute approach is not uncommon either. As a compromise, if there was a built in method which could get certain things (but not set them) then that would work too. `$mySelect.select2('getInstance')` could just get the bits that are considered "safe" to expose.

**Comment by alexweissman** [comment]
Keep in mind also, that modifications to the internals of Select2 should be possible with custom adapters/decorators.  

Can you provide examples of other jQuery plugins that have a `getInstance` method?  

Incidentally, this seems like a perfect example of how Javascript's lack of visibility scoping can be frustrating.  Perhaps we need a rewrite of Select2 into [Typescript](https://www.typescriptlang.org/docs/handbook/classes.html#public-private-and-protected-modifiers) more badly than we realize 😁 

At any rate, I've merged in @NadeemAfana's BC fix for release on `4.0.6-rc.1`, so this should solve the problem for the time being.

**Comment by NadeemAfana** [comment]
The tests now run for both jQuery 1.x and 2.x. This allows us to see if there is any discrepancy in the future.

**Comment by NadeemAfana** [comment]
Re-opening.

**Comment by jamessaget** [comment]
Hello,

I have read through issue #5071 which lead me here. What I am trying to achieve is change a config option after initialisation and stumbled into the issue stated here https://stackoverflow.com/questions/37016655/select2-cannot-read-property-query-of-null regarding the error thrown within the dataAdapter.

```javascript
$('.country_select').on('select2:opening', (e) => {
   if($(e.target).data('select2').options.options.minimumResultsForSearch == 5) return
   $(e.target).data('select2').options.options.minimumResultsForSearch = 5;
   let options = $(e.target).data('select2').options.options;
   $(target).select2('destroy');
   $(target).select2(options);
})
```

Any suggestions would be appreciated

**Pull request closed without merging**
