### PR TITLE
fix : #3121 - option to force dropdown positioning above/below

### PR DESCRIPTION
**Pull request by DVD27**
This pull request includes a
- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made :
- Add an option for choice the dropdown position on open (above, below or both) (issues #3121)

### CODE REVIEW

**Comment by sashamjolnir** [comment]
Why this PR is not merged?

**Comment by AaronJWhite** [comment]
I could also use this. Is there a reason this PR has not been merged?

**Comment by mnsrv** [comment]
Code at line 181 of attachBody.js is inside else condition, if dropdownPosition option is not set.

**Comment by ParadoxalManiak** [comment]
Will this be merged ? It would be really useful to be able to select where the dropdown will appear.

**Comment by mavame** [comment]
Would love to see this get merged!

**Comment by Obermeijer** [comment]
Same, I need this functionality as well as I'm facing a design that doesn't allow displaying dropdown elements above.

**Comment by smoleniuch** [comment]
That would be awesome if it will be merged

**Comment by RaykPlatzek** [comment]
Agreed this would be great

**Comment by nickwlker** [comment]
Agree! +1

**Comment by velis74** [comment]
This PR works great! Please merge, it doesn't change anything, it only adds.

**Comment by Jalen929** [comment]
Agree

**Comment by denodster** [comment]
We need this fix at my company we've been running into this issue with our users.

**Comment by jpic** [comment]
Do we really need to add this as an optional feature or should we rather upgrade the current behaviour ?

**Comment by jochenberger** [comment]
I suggest changing `'both'` to `'auto'`.

**Comment by joeliomason** [comment]
Is this going to be merged in?? Really need this

**Comment by alexweissman** [comment]
Please don't add irrelevant, noisy comments.  Select2 has so many open issues and PRs, it is impossible for one person to review them all.  

All you're going to do is scare me off, and then nothing will get fixed 😛

**Comment by zibibbalibbo** [comment]
This PR works great! Just tested, really can't understand why it's still not merged.

**Comment by TomasLudvik** [comment]
Wow this is sad situation, someone solves it pretty nice way, many people asks to include it in the library and after three years it is closed by stale bot. Came looking for exactly this solution, now I have to consider some other library.

**Pull request closed without merging**
