### PR TITLE
Add dist i18n js for es-MX

### PR DESCRIPTION
**Pull request by jtapia**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [x] Translation

The following changes were made

- Add es-MX js file

### CODE REVIEW

**Comment by simi** [comment]
Is there any difference compared to https://github.com/select2/select2/blob/master/src/js/select2/i18n/es.js? I wasn't able to find any.

**Comment by kevin-brown** [comment]
This appears to be the same as `es.js`, which is what will be used if `es-MX` is specified as the language. Select2 will build a fallback chain, and that is the second one (out of three) in the chain.

**Comment by jtapia** [comment]
I think that approach is not the correct one, I mean, we have the same languague 'spanish' but we have different idioms, so maybe you should add those different files for each spanish languaue country

**Comment by jtapia** [comment]
@simi on this case we use the same words, but maybe on Colombia they don't, so we should include all of those files

**Comment by simi** [comment]
That's ok to add new translation, but I wasn't able to find any difference between current es.js and your submited es-MX.js. It is useless to have same file twice in repository and thanks to fallbacks, es-MX language will use es.js translation file.

**Comment by jtapia** [comment]
I started looking into an issue inside `spree` admin, `http://localhost:3000/javascripts/select2_locale_es-MX.js` and at the end it took me here on `select2`, and that's because you're matching any `es-` locale to `:es` and on this case is wrong because `es-MX` is the correct locale, not `:es`

**Pull request closed without merging**
