### PR TITLE
Fix_allowClear_bad_allign_bug

### PR DESCRIPTION
**Pull request by chrisNom**
Fixes 3 issues #4470, #4555 and #3906

This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- modified the css class for and added bottom-margin 5px .select2-container--default .select2-selection--multiple .select2-selection__clear

### CODE REVIEW

**Comment by jpic** [comment]
Works for me, why did you choose 5px for the bottom margin ? Is it just to reflect the top margin or is there any other reason ? Another user used 10px in their fork https://github.com/pculture/unisubs/commit/d2474675c94b473cb2c5257e0e1fe543446f46ed I'm wondering why but can't find a reason.

Also, can you get rid of the extra commit please ?

**Comment by bendk** [comment]
I picked 10px mostly just because that's what I saw.  It also seemed to line up with the line-height, which seemed good to me.  I'm sure it's not the only, or the best, way to do it though.

**Comment by chrisNom** [comment]
I picked 5px to be symmetrical to the top 5px margin. 10px will work but would broaden the margin between lines of multiselect, and I did not want to have it.

**Comment by jpic** [comment]
@bendk does that make sense for you ? will it be ok for you if we change it
to 5px in the core ?

**Comment by bendk** [comment]
Sorry for not replying to this, but 5px sounds fine by me.

**Pull request closed without merging**
