### PR TITLE
Fixes #3712 Allowing Pasting tags from spreadsheet

### LINKED ISSUE #3712: Paste tags with newlines, use textarea as search input?
Is it possible to be able to paste tags into the search box that are separated by newlines, so the tags themselves can contain spaces? It seems that, because an `<input type="text" />` is used, that newlines are converted to spaces before they arrive at the tokenizer function. Is it possible to use a `<textarea>` as search box instead, so that newlines are preserved?

### PR DESCRIPTION
**Pull request by denodster**
I was trying to make an easy way for clients to copy and paste tags from a spreadsheet, but I was unable to do this because select2's use of a 'search' input would remove all newline characters from the pasted input. replacing the search text input with a textarea removes this limitation.

This pull request includes a

- [x] Bug fix
- [x] New feature

The following changes were made

Replaced `<input type="search" />` with `<textarea></textarea>`
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by denodster** [comment]
clearly this needs more work.

**Comment by denodster** [comment]
What do I need to do to get this looked at?

**Comment by denodster** [comment]
@alexweissman are you a new maintainer? what do I need to do to get this in?

**Comment by alexweissman** [comment]
I'm a "maintainer-in-training".  My main goal is to improve the documentation and get the obvious bug fixes merged in.

This looks like a good feature, but it has the potential to create breaking changes for anyone who is expecting an `input` field.  Can we make this a configuration option instead?  Maybe something like `searchElement` that can take on a value of either `input` (default) or `textarea`?

**Comment by denodster** [comment]
sounds good, I'll get to work.

**Comment by denodster** [comment]
@alexweissman I've sorted this out and written the change to config. The code passes tests and I've tested this in our environment. if searchElement = 'textarea' a textarea will be used, otherwise an input will be used as usual, so this should not change backward compatibility.

**Comment by denodster** [comment]
documentation pull request here: https://github.com/select2/docs/pull/27

**Comment by kevin-brown** [comment]
Unfortunately this pull request contains files in the `dist` folder, and as a result there is a merge conflict.

If you are still interested in making this contribution, feel free to remove the `dist` changes from this pull request and leave a comment asking for this to be re-reviewed.

**Comment by denodster** [comment]
@kevin-brown I've done this, how does it look now?

**Comment by denodster** [comment]
@kevin-brown @alexweissman Just pinging this again, can I merge it in?

**Comment by kevin-brown** [comment]
Is there a reason why we wouldn't just switch it to always use a `<textarea>` instead of giving the option of both? (aside from backwards compatibility reasons)

**Comment by Neokyuubi** [comment]
I hope this can be merged soon, thank you so much for you continuing to work on this one.

**Comment by denodster** [comment]
@kevin-brown none really, I only did it to satisfy @alexweissman (several comments above)

**Comment by denodster** [comment]
Anything I can do to help this along?

**Comment by denodster** [comment]
@kevin-brown I've updated this with the latest.

**Comment by denodster** [comment]
@kevin-brown can you give me a status update as to what your plan is here?

**Comment by denodster** [comment]
stalebot...

**Pull request closed without merging**
