### PR TITLE
Flat Theme Added

### PR DESCRIPTION
**Pull request by techhysahil**
Flat theme for Select2 #3957

### CODE REVIEW

**Comment by mik-laj** [comment]
+1, if it looks like this: http://codepen.io/techhysahil/pen/qbrqWG

**Comment by techhysahil** [comment]
Is anybody active here to merge this one.

**Comment by kevin-brown** [comment]
This would probably be better broken off into a separate package, [similar to the Bootstrap theme](https://github.com/select2/select2-bootstrap-theme), which we can link to in the documentation.

**Comment by techhysahil** [comment]
That is nice suggestion. i will let you know once it's done.

**Comment by techhysahil** [comment]
Hey @kevin-brown, i have added a new Repo https://github.com/techhysahil/select2-Flat_Theme/tree/master. Now you add it in documentation i suppose,

**Pull request closed without merging**
