### PR TITLE
correct typo in pt.js

### PR DESCRIPTION
**Pull request by simi**
I have no knowledge about portuguese. This is based on #4294.

### CODE REVIEW

**Comment by kevin-brown** [comment]
Thanks!

**Comment by pedro-mendonca** [comment]
This is perfect now 👍 
Thanks!

**Comment by simi** [comment]
@kevin-brown I missed to recompile dist here.

**Comment by kevin-brown** [comment]
@simi No worries, we recompile dist from time to time. It's usually better to only include source changes in a pull request, as it avoids conflicts within the dist files.

**Pull request merged**
