### PR TITLE
move GitHub related markdown files into .github

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by alexweissman** [comment]
This is kind of cool...didn't know Github supported this.

**Comment by PeterDaveHello** [comment]
Do I need to fix the conflicts which means this change is acceptable? If it's not acceptable, feel free to close it, thanks.

**Comment by alexweissman** [comment]
Yeah, if you want to rebase the changes on the current `master` branch, that would be great!

**Comment by PeterDaveHello** [comment]
Sure thing, I'll do it soon, thanks.

**Comment by PeterDaveHello** [comment]
Updated!

**Comment by alexweissman** [comment]
Thanks!  I'm not sure if Github will automatically redirect links to any of these files but...I guess we'll find out!

**Pull request merged**
