### PR TITLE
Fix select2#5378 ie11 specific focus issue with select2#5453

### PR DESCRIPTION
**Pull request by jbosse**
This pull request includes a

- [ X] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

Resolved merge conflicts from https://github.com/select2/select2/pull/5453 developed by @vandernorth

There is bug with tags in IE11. This fixes it. Two previous Issues were closed without a fix. Please do not close unless merged.

### CODE REVIEW

**Comment by RobertDiebels** [comment]
Can someone merge this? We're dependent on a fork right now and we'd like to move back to this repository.

**Comment by cavias** [comment]
Since we're experiencing the same issue, we would also like to see this merged. Wondering why multiple issues and pull requests keep getting ignored.

**Comment by jbosse** [comment]
It looks like the PR has some new conflicts. Hopefully I can find some time today or tomorrow to resolve them. 😬

I can’t speak for this project but I have maintained other open source projects and from experience they can often take a back seat to many other priorities. Especially without a financial sponsor.

**Comment by cavias** [comment]
It appears there is a request of help from the maker for tests https://github.com/select2/select2/issues/5516#issuecomment-500401680

**Pull request closed without merging**
