### PR TITLE
Fixing focus issue with wrapping labels

### PR DESCRIPTION
**Pull request by stretch4x4**

### CODE REVIEW

**Comment by stretch4x4** [comment]
Not sure if this is the best place for this code but it does resolve the issue I am seeing with labels in #4203

**Comment by kevin-brown** [comment]
Now that we've determined that the issue is that a `click` event is being generated on the label, why is the `click` event being generated when Select2 is opened?

This seems like it _might be_ a band-aid over a larger issue.

**Comment by stretch4x4** [comment]
Actually that is a really good point, I assumed it was because they were nested but now that I think about it that doesn't make a lot of sense..
I will see if I can trace the click and find some more info.

**Comment by stretch4x4** [comment]
Turns out it is being generated for a standard one: https://jsfiddle.net/2kt7z8wu/3/
I think the issue is that the same behaviour happens and the hidden select gets focus..

**Pull request closed without merging**
