### PR TITLE
fix error : "Uncaught ReferenceError: require is not defined"

### PR DESCRIPTION
**Pull request by dbwhddn10**

### CODE REVIEW

**Comment by kevin-brown** [comment]
This should also be fixed in [`jquery.select2.js`](https://github.com/select2/select2/blob/9318980651e5bf471c412834139a03bf5de54f94/src/js/jquery.select2.js).

**Comment by dbwhddn10** [comment]
@kevin-brown this is fatal error: see https://jsfiddle.net/dbwhddn10/7zek638x/

**Comment by kevin-brown** [comment]
Right, I understand that hidden inputs are broken right now because of this. I was just pointing out that we've also got an issue when loading in jquery.mousewheel, but it's being silenced and it might be useful to also get that fixed.

**Comment by kevin-brown** [comment]
Committed in https://github.com/select2/select2/commit/da1ec4e02865f3b23d7634eba509e3438d4ab874.

**Pull request closed without merging**
