### PR TITLE
Update select2.js

### PR DESCRIPTION
**Pull request by qingyuexiao**
add searchable option so we can choose to use the search bar or not.

### CODE REVIEW

**Comment by kevin-brown** [comment]
We recommend using `minimumResultsForSearch: Infinity` when you want to permanently disable the search.

**Comment by kevin-brown** [comment]
Reopening this until this is documented.

**Comment by qingyuexiao** [comment]
I see, thanks. The property is described in the _options_ part. Maybe show in _examples_ will make it easier to get.

**Comment by qingyuexiao** [comment]
I find sometimes the $dropdown is not positioned right when showing above - see the shotcut below

Test results shows that the initial width of $dropdownContainer is 0 and it makes the outerHeight of $dropdown incorrect. I change the excute order of _resizeDropdown & _positionDropdown funciton in AttachBody.prototype._showDropdown(line 3983,3984), and it works. 





发件人：徐秋琼 
 
中国电信上海理想信息产业（集团）有限公司
增值应用业务部 

地址：上海市杨高南路5788号中国电信信息园区B4楼
电话：021-20305588-3073
传真：021-20305150
手机：18901681280   
Email：18901681280@189.cn 
 From: Kevin BrownDate: 2015-02-27 03:05To: select2/select2CC: qingyuexiaoSubject: Re: [select2] Update select2.js (#3077)We recommend using minimumResultsForSearch: Infinity when you want to permanently disable the search.

**Comment by qingyuexiao** [comment]
I find sometimes the $dropdown is not positioned right when showing above - see the shotcut below

Test results shows that the initial width of $dropdownContainer is 0 and it makes the outerHeight of $dropdown incorrect. I change the excute order of _resizeDropdown & _positionDropdown funciton in AttachBody.prototype._showDropdown(line 3983,3984), and it works. 





From: qingyuexiao 
 From: Kevin BrownDate: 2015-02-27 03:05To: select2/select2CC: qingyuexiaoSubject: Re: [select2] Update select2.js (#3077)We recommend using minimumResultsForSearch: Infinity when you want to permanently disable the search.

**Pull request closed without merging**
