### PR TITLE
Improve usability of select2 in node environment with browserify

### PR DESCRIPTION
**Pull request by leftmostcat**
There are a couple issues that result from select2 being require()d in a node environment and then browserified for use client-side, as set out in #3282 and #3287. This PR solves both of these issues.

### CODE REVIEW

**Comment by tulbox** [comment]
Will this PR be merged or has it already been dealt with in the main branch?

**Comment by kevin-brown** [comment]
This has not yet been merged as we still need to look into it.

**Comment by tulbox** [comment]
@kevin-brown - thanks for the prompt response! And @leftmostcat for the fork to potentially use in the meantime.

**Comment by digitalkaoz** [comment]
any chance this gets merged?

**Comment by kevin-brown** [comment]
This should have been fixed by https://github.com/select2/select2/commit/8edf3c64082be59b9506f3ad6dd84073b6eb5841.

**Pull request closed without merging**
