### PR TITLE
he.js

### PR DESCRIPTION
**Pull request by yonihbc**

### CODE REVIEW

**Comment by kevin-brown** [comment]
Thanks for the translation!

**Comment by yonihbc** [comment]
when will it be available for the select2 from cdn?


John Greenberg
Haifa, Israel
yonihbc@hotmail.com

P Please consider the environment before printing this e-mail 

Date: Wed, 18 Mar 2015 06:15:48 -0700

**Comment by kevin-brown** [comment]
It should be available when the final release rolls out, sometime in the next few days.

**Comment by yonihbc** [comment]
take a look at the merged file - i think it override the en.js file


John Greenberg
Haifa, Israel
yonihbc@hotmail.com

P Please consider the environment before printing this e-mail 

Date: Wed, 18 Mar 2015 06:23:21 -0700

**Comment by kevin-brown** [comment]
I fixed it when I recompiled the translations.

**Comment by yonihbc** [comment]
ok thanks
is it possible to ask you something?when i have tags in the multiple selectand i click on "x" to remove them - the popup of all the options shows up - can that be disabled?


John Greenberg
Haifa, Israel
yonihbc@hotmail.com

P Please consider the environment before printing this e-mail 

Date: Wed, 18 Mar 2015 06:45:11 -0700

**Pull request merged**
