### PR TITLE
Add scrollAfterSelect as a configurable option for multiselect dropdowns to allow toggling of highlightFirstItem() behaviour

### PR DESCRIPTION
**Pull request by boweihan**
Resolves issue for multiselects using closeOnSelect: false that caused the list of results to scroll to the first selection after each select/unselect. This behaviour was intentional to deal with infinite scroll UI issues but it created an issue with multiselect dropdown boxes of fixed length. This pull request adds a configurable option to toggle between these two desirable behaviours.

This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Added configurable option "scrollOnSelect"
- If set to TRUE multiselect dropdowns will scroll to the first item on the list after "select" or "unselect" events (i.e. for infinite scroll case)
- If set to FALSE highlight will remain on selected item.

I ran into this issue when implementing select2 multiselect dropdowns with a fixed item length. It was confusing to have the focus move to the first item after each select/unselect event.

If this is related to an existing ticket, include a link to it as well.
https://github.com/select2/select2/pull/4869 - is tagged needs more work. I noticed it hasn't been touched for a while so I'm following up on this.
https://github.com/select2/select2/issues/4417 - discussion for where this problem originated. (this particular commit - https://github.com/select2/select2/commit/9f581285d88128b29a01fc1e5fd2d445d610b553)

### CODE REVIEW

**Comment by alexweissman** [comment]
Nice!  Can you add some tests for this?

**Comment by boweihan** [comment]
@alexweissman I added some tests to focusing-tests.js to verify the configurable option behaviour. I also changed the default for scrollAfterSelect to be "true" to avoid modifying existing implementations (this was debatable to me since it means that anyone using a non-paginating dropdown will need to explicitly set { scrollAfterSelect: false} but I feel it's justifiable to avoid introducing breaking changes for pagination users).

**Comment by alexweissman** [comment]
I have to say though, I am confused by the explanation given here: https://github.com/select2/select2/issues/4417#issuecomment-244741804

@jgbishop and @AlexanderLeonov, can you explain exactly why the `highlightFirstItem` method ever needs to be called, even in the infinite scroll (pagination) case?

**Comment by calumah** [comment]
Any update on this PR ?

I'm using large multi-select with only few value to select and this bug/feature is very annoying for users :/

I'm trying to do a monkey patching for disabling highlightFirstItem() function but I can't find the correct syntax / path ...

**Comment by jsJunky** [comment]
Sorry if this is spamming but I was wondering what the progress of this PR for acceptance is.

**Comment by pedrofurtado** [comment]
@kevin-brown  @alexweissman Is this PR ready for merge? If so, merge it, please!

**Comment by jsJunky** [comment]
@marcioJesus Would that not be done during a build phase?

**Comment by marcioJesus** [comment]
@jsJunky I don't understand your question very well. But what I meant is that only worked for me when I added of 'scrollAfterSelect' validation in call of 'highlightFirstItem()' in the the file 'dist\js\select2.js' unlike of  'src/js/select2/results.js'  :)

**Comment by jsJunky** [comment]
@marcioJesus Usually most projects do not require you to manually update the final built files. Those will be handled by the build system that will grab all necessary files and build them into a file in the `dist`. Look at the Gruntfile `compile` task and look into `grunt` to see how this is achieved.

**Comment by cgomezmendez** [comment]
Any update on this?

**Comment by dinandmentink** [comment]
Is there an update on this? Really looking forward to this being fixed?

**Comment by huseyinbirtan** [comment]
Following modification on select2.js helped for now

c.prototype.highlightFirstItem = function() {
             return false;
},

**Comment by boweihan** [comment]
Let me know if there's anything I can do to help push this through!

**Comment by pedrofurtado** [comment]
@kevin-brown @alexweissman Any news?

**Comment by dinandmentink** [comment]
I have several projects where a monkeypatch is active untill this is released. Is there any estimate on when this will be released? Is there anything I can help with to get this released?

**Comment by pedrofurtado** [comment]
@dinandmentink I've created a fork of select2 with some monkeypatches of community. See the repo: https://github.com/pedrofurtado/select2

See also the diff: https://github.com/select2/select2/compare/develop...pedrofurtado:develop

**Comment by pedrofurtado** [comment]
@dinandmentink Test using this fork to check if the issues are resolved, at least until a new official version is released. I'm using this version in my company's projects

**Comment by pedrofurtado** [comment]
@boweihan I added some docs explaining this new property ( https://github.com/select2/docs/commit/165f9459378c0c5699fdc79e391129fd754000cc ).

**Comment by arning** [comment]
I get following error, when I use the 'develop' version (instead of 4.05):
`Uncaught TypeError: Cannot set property 'selected' of undefined`

This code causes the error
`data.selected = true;`
Line 3173 of select2.js

Do I need to configure select2 to make this version work?

**Comment by pedrofurtado** [comment]
@arning The `develop` branch is not the best place to use as dependency. You need to use the released versions, like 4.0.5, and so on. Using develop or master of any Github repository you are assuming a risk of some temporary instability.

**Comment by arning** [comment]
@pedrofurtado
Alright, understood. 
Then, I hope, that this issue will be resolved in the next regular release. Since we are using large multi-select dropdown lists, and this behaviour is quite annoying for our users.

**Comment by callmejed** [comment]
Cheers this is exactly what I needed. May I point out that you say the configurable option is "scrollOnSelect" while the code you changed in the js is "scrollAfterSelect".

**Pull request merged**
