### PR TITLE
Fix select2#5378 ie11 specific focus issue.

### PR DESCRIPTION
**Pull request by vandernorth**
This pull request includes a fix for #5378 

- [X] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made
- Existing IE detection moved up a few lines so they are declared before they are used.
- On the focusout event of the search-input use the existing variable to detect IE
- If IE, and the event comes from the <body> tag, refocuses so we can keep typing

Issue: https://github.com/select2/select2/issues/5378

### CODE REVIEW

**Comment by exhtml** [comment]
Hi! First of all thanks so much for your superb plugin! When do you think this fix could be ready? Thank you!

**Comment by LastZactionHero** [comment]
Thanks for the fix! This fixes an issue for me, would love to see it merged in.

**Comment by vandernorth** [comment]
@kevin-brown can you merge this request?

**Comment by kevin-brown** [comment]
I think this may actually be fixed in 4.0.8, which was released the other day and corrected some unexpected focus issues.

Is there any chance you can confirm the original issue still exists?

**Comment by LastZactionHero** [comment]
4.0.8 does not resolve the IE11 issue for me. For me, issues manifests as only being able to type a single character. We've been using the changes from this PR in production for a few months.

**Comment by tpetry** [comment]
I can confirm that 4.0.8 does not solve the bug. But the submitted pull-request does not solve the problem completely either:
* For chrome a tag is created after entering the first 2 characters
* For ie11 the focus is lost after entering the first tag

**Pull request closed without merging**
