### PR TITLE
Add multiple selection specification to docs

### PR DESCRIPTION
**Pull request by marcaparent**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Adding the `multiple` specification to the docs 

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by subssn21** [comment]
Multiple does not have to be added to a select to enable tags support. Single select tags (which allows you to select an already entered option or create your own are allowed)

Recommend closing the pull request as the documentation changes would be inaccurate

**Comment by marcaparent** [comment]
You are indeed right, thanks for this clarification. 

I still think some improvement is possible in the documentation, as it would make sense to explain both possibilities. I've been faced more than once with trying to setup a multiple tags select input and always forget to include the multiple attribute. I'll edit my pull request to clarify, up to you to merge or not.

**Comment by subssn21** [comment]
I would clarify that the multiple attribute is for the HTML, perhaps an example too just so people aren't confused that you are not saying that it is a config option on select2.

Once that's done I would recommend that this gets merged.

**Comment by marcaparent** [comment]
I added an example for a single select element, to keep the default multiple example first.

**Comment by alexweissman** [comment]
I think this can be integrated fairly easily. I'll rewrite it a bit, to clarify exactly what "tagging" is.

**Pull request merged**
