### PR TITLE
select2 treeview

### PR DESCRIPTION
**Pull request by maliming**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

select2 treeview #3269 

example: [select2-treeview](https://github.com/maliming/select2-treeview)

$("#test").select2({
      treeview:true
});

### CODE REVIEW

**Comment by mtangoo** [comment]
commenting just to make sure I get notified when this is merged

**Comment by trostli** [comment]
This looks awesome!

**Comment by jpic** [comment]
I think this can be merged after it has tests and documentation.

**Comment by maliming** [comment]
@jpic 
In fact, I'm not good at front-end development. If someone can help that is the best.

**Comment by jpic** [comment]
Sure, what's your question ?

**Comment by maliming** [comment]
What I mean is that everyone can modify my code, add related tests and documentation, then submit the PR. 😊

**Comment by jpic** [comment]
Can we leave it open meanwhile ? Perhaps someone will like to help.

**Comment by maliming** [comment]
Of course, select2 give US a lot of help, we want to make it better!

**Pull request closed without merging**
