### PR TITLE
Allow pasting multiple lines into the search field for tokenization

### LINKED ISSUE #3712: Paste tags with newlines, use textarea as search input?
Is it possible to be able to paste tags into the search box that are separated by newlines, so the tags themselves can contain spaces? It seems that, because an `<input type="text" />` is used, that newlines are converted to spaces before they arrive at the tokenizer function. Is it possible to use a `<textarea>` as search box instead, so that newlines are preserved?

### PR DESCRIPTION
**Pull request by denodster**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-Changes input to select
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by denodster** [comment]
stalebot closed my previous PR

**Comment by denodster** [comment]
Hey @kevin-brown I've noticed that you keep touching the piece of code that this does, and while I'm happy to keep this updated on my end, do you think that it might be a good time to merge it in? Are there any apprehensions you have to merging it? is there anything you want me to change?

**Comment by denodster** [comment]
Also I see with your latest changes I'm no longer allowed to reference 'this' can you advise on how exactly I should get the preferences?
Should I just change the input to a textarea? the setting was alexhoffman's idea and I did it so that I could get this merged, but a textarea is really better all around because it doesn't drop tab and newline characters.

**Comment by denodster** [comment]
reopened form https://github.com/select2/select2/pull/4795

**Comment by kevin-brown** [comment]
Hi again, it's been a while. I haven't merged this in yet because I have some hesitations around side-effects. And I honestly haven't been in the mood to try to walk through this manually and get it running locally.

* This needs to be styled to match the existing search box, and that includes not allowing it to actually go across multiple lines
* Do we know what the accessibility side effects of this are? Pretty much all of the examples around accessibility within a comboxbox involves an `<input />` and I'd rather not break all of the work we've done in this area to align us with the standards.
* We shouldn't allow for both `<input />` and `<textarea>`, that just sounds like a mess. We need to be aware of the fact that this _will be_ a breaking change and therefore right now, as we prepare for 4.1.0, is the best time to consider making this change.
* Does this have any impact on the keyboard shortcuts that we support?

**Comment by denodster** [comment]
@kevin-brown Thanks for the response, I'll change this patch back into a change rather than a configurable and work on some modeling to show if it effects css.

**Comment by kevin-brown** [comment]
@denodster I give you credit for following this patch through for 3 years (and counting) and I apologize for that. I can help you out a bit with the styling if we can get the functional parts of it nailed down (keyboard accessibility + shortcuts).

**Comment by denodster** [comment]
Not Stale.

**Comment by kevin-brown** [comment]
Still not stale.

**Comment by Apezdr** [comment]
Any chance of this getting attention?

**Comment by denodster** [comment]
I need to put together some testing of some kind, though I've got other stuff going on right now, if you are inclined to put together a side by side where you compare this version with the main trunk that would be helpful. we need to show that this changes doesn't break screen readers and css.

**Comment by denodster** [comment]
Not Stale

**Comment by kevin-brown** [comment]
Still watching this, thanks for keeping it not stale. 👍

**Comment by kevin-brown** [comment]
I pushed up a handful of commits but there is still a failing test around sizing where the text box is now a few pixels too wide all of a sudden. I don't currently have the time to look into this (it's getting late) but I'm planning on tackling this next time, since I want to get this into the next beta of Select2 4.1.0.

**Comment by denodster** [comment]
@kevin-brown thanks for doing that, I've been swamped lately with other things at my company but I still intend to return to this, I'll try to take a look as soon as my schedule gives me the opportunity.

**Comment by kevin-brown** [comment]
No worries, I was busy for the last few months so I totally understand.

I think I figured out what was causing the failing test and corrected that issue. I'm going to let this stay open for a little longer (not sure if minutes or days) so eyes can check it out and then I'll merge it in for the next release.

**Pull request merged**
