### PR TITLE
Uses tabs for creating tags as a default feature

### PR DESCRIPTION
**Pull request by davilious**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Allows the use of tabs to create tags by triggering the proper events, `results:select`

If this is related to an existing ticket, include a link to it as well.

https://github.com/select2/select2/issues/3359#issuecomment-214272255

I believe previous versions of Select2 added it as a default feature without the need of setting it via options. 

I run the tests and everything seems to be fine.

I hope it helps.

### CODE REVIEW

**Comment by Jan-Kruse** [comment]
Works perfectly smooth, thanks a lot :balloon::tada::confetti_ball:

**Comment by drush** [comment]
+1

**Comment by mlorant** [comment]
@davilious While the PR is not merged/released, do you have a built version of select2 with this patch or is there any way to do the same by overriding events handlers in my own code?

**Comment by davilious** [comment]
Hey @mlorant, what I did was to include the change in the uncompressed version **leaving a comment** to fix it when the merge happens. [Here a fiddle](https://jsfiddle.net/bs3wctwg/) where you will find the context but make sure you have the **same version (4.0.2)** and **replace it** when it is merged or new versions of this change take place.

**Comment by carldanley** [comment]
Any update on having this PR added to the next release?

**Comment by kevin-brown** [comment]
Just a note: This won't be landing as a default feature because it's a breaking change.

My standard recommendation is to look into `selectOnClose` to see if it's what you are actually looking for.

**Comment by drush** [comment]
@kevin-brown selectOnClose addresses this for my use case, thanks for referencing that. I hadn't seen it before.

**Comment by davilious** [comment]
@kevin-brown thx for the reference, I wasn't aware there was an option already which works perfectly fine. Closing this PR.

**Comment by davilious** [comment]
Just for the records. The `selectOnClose` option is not enough for my needs because you can't leave the field blank, it is a little annoying indeed. Below a demo, try to delete the tag set.

[Select2 - issue#4325 demo](http://codepen.io/davilious/pen/542c85c91008201f995b686be16de559?editors=1010)

However, I understand my pull-request might be a little drastic, people may want to use the "Tab" key to close the dropdown instead of selecting one option.

**Comment by SatanEnglish** [comment]
Same Issue here even using the clear for the dropdown selects the first item

**Comment by rob101** [comment]
+1

**Pull request closed without merging**
